{{- if .Values.simulator.enabled  }}


apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.simulator.secretName | default "adcs-simulator-secret" }} 
  namespace: {{ .Release.Namespace }} 
type: Opaque
data:
  password: cGFzc3dvcmQ= # password
  username: dXNlcm5hbWU= # username

{{- end  }}    